on:
  push:
    branches: ['main', '*.*.x']
    paths:
      - composer.json

jobs:
  sync-repo-description:
    if: github.ref_name == github.event.repository.default_branch
    uses: typhoon-php/.github/.github/workflows/sync-repo-description.yml@main
